name: Bug report
description: Report titlechanger bugs.
labels: [ "bug" ]
body:
  - type: textarea
    attributes:
      label: Error
      description: |
        We need all of the stack trace! Do not cut off parts of it. Please do not use attachments.
        If you prefer, you can use a paste site like https://paste.gg.
      value: |
        ```
        paste your stack trace or a paste.gg link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Modloader
      description: The Mod Loader running on your client
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actions to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue. Anything helps!
    validations:
      required: true

  - type: textarea
    attributes:
      label: TitleChanger version
      description: The version of TitleChanger
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below, if any.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. You are running the latest version of TitleChanger from [our downloads page](https://modrinth.com/mod/mctitlechanger/versions).
        2. Please confirm if the Mod Loader is used correctly.
        3. Check if there have been the same issues before.
